parameters:
#    product.example.class: Product\Bundle\Example

#services:
#    product.example:
#        class: %product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    Product.antispam:
        class: Product\Bundle\Antispam\ProductAntispam