parameters:
#    oc_platform.example.class: OC\PlatformBundle\Example

services:
#    oc_platform.example:
#        class: %oc_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
